<?php
namespace warnemuende\model;

require_once 'PHPUnit/Framework.php';

require_once dirname(__FILE__).'/../../../warnemuende/model/Model.php';

// This test bases on these demo models
require_once "demomodels.php";

/**
 * Test class for Model.
 * Generated by PHPUnit on 2010-08-18 at 17:04:50.
 */
class ModelTest extends \PHPUnit_Framework_TestCase {

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        mysql_connect("localhost", "modeltester", "test");
        mysql_select_db("modeltester");
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        $m = new MySqlInitialization();
        $m->setTableName(Page::getTableName());
        $m->dropTable();
    }

    public function testGetFields() {
        $t = Page::getFields();
        print_r($t);
        $this->assertEquals(count($t), 5);
        $this->assertEquals($t[0], "id");
    }

    public function testGetFieldOption() {
        $this->assertEquals(Page::getFieldOption("slug", "type"), "text");
    }

    public function testInitDatabase() {
        $result = mysql_query("show tables;");
        if (mysql_num_rows($result) == 0) {
            Page::initDatabase();
            $result = mysql_query("show tables like '".Page::getTableName()."'");
            $number = mysql_num_rows($result);
            $this->assertEquals($number, 1);
        } else {
            $this->fail("Need an empty database for security reasons.");
        }
    }

    /**
     * @todo Implement testGetIndices().
     */
    public function testGetIndices() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testDelete().
     */
    public function testDelete() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testGetField().
     */
    public function testGetField() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testSave().
     */
    public function testSave() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testSetField().
     */
    public function testSetField() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }
}

?>
