<?php
namespace warnemuende\model;

require_once 'PHPUnit/Framework.php';

require_once dirname(__FILE__).'/../../../warnemuende/model/Model.php';
require_once dirname(__FILE__).'/../../../warnemuende/model/MySqlInitialization.php';
// This test bases on these demo models
require_once "demomodels.php";

/**
 * Test class for MySqlInitialization.
 * Generated by PHPUnit on 2010-08-17 at 16:28:52.
 */
class MySqlInitializationTest extends \PHPUnit_Framework_TestCase {
    /**
     * @var MySqlInitialization
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        mysql_connect("localhost", "modeltester", "test");
        mysql_select_db("modeltester");
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
    }

    /**
     * @todo Implement testInit().
     */
    public function testInit() {
        $result = mysql_query("show tables;");
        if (mysql_num_rows($result) == 0) {
            Page::initDatabase();
            $result = mysql_query("show tables like '".Page::getTableName()."'");
            $this->assertEquals(mysql_num_rows($result), 1);
            @mysql_query("drop table ".Page::getTableName());
        } else {
            $this->fail("Testing can lead to different problems - please give me an empty database.");
        }
    }

    /**
     * @todo Implement testSetField().
     */
    public function testSetField() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testSetTableName().
     */
    public function testSetTableName() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testGetIndices().
     */
    public function testGetIndices() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testAddIndex().
     */
    public function testAddIndex() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testGetCreateTableStatement().
     */
    public function testGetCreateTableStatement() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }
}
?>
