<?php
namespace warnemuende\model;

require_once 'PHPUnit/Framework.php';

require_once dirname(__FILE__).'/../../../warnemuende/model/Model.php';
require_once dirname(__FILE__).'/../../../warnemuende/model/MySqlInitialization.php';
// This test bases on these demo models
require_once "demomodels.php";

/**
 * Test class for MySqlInitialization.
 * Generated by PHPUnit on 2010-08-17 at 16:28:52.
 */
class MySqlInitializationTest extends \PHPUnit_Framework_TestCase {
    /**
     * @var MySqlInitialization
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        mysql_connect("localhost", "modeltester", "test");
        mysql_select_db("modeltester");
        $this->object = new MySqlInitialization();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
    }

    public function testInit() {
        $result = mysql_query("show tables;");
        if (mysql_num_rows($result) == 0) {
            Page::initDatabase();
            $result = mysql_query("show tables like '".Page::getTableName()."'");
            $number = mysql_num_rows($result);
            $this->assertEquals($number, 1);
        } else {
            $this->fail("Need an empty database for security reasons.");
        }
    }

    public function testDropTable() {
        $result = mysql_query("show tables like '".Page::getTableName()."'");
        if (mysql_num_rows($result) == 1) {
            $this->object->setTableName(Page::getTableName());
            $this->object->dropTable();
            $result = mysql_query("show tables like '".Page::getTableName()."'");
            $this->assertEquals(mysql_num_rows($result), 0);
        } else {
            $this->fail("Unable to test table dropping.");
        }
    }


}
?>
